ifeq (androideabi,$(findstring androideabi,$(TARGET)))

CC := $(TARGET)-gcc
AR := $(TARGET)-ar

else

CC ?= gcc
AR ?= ar

endif

CFLAGS += -fPIC

.PHONY: all
all: $(OUT_DIR)/libstb-image.a

$(OUT_DIR)/stb_image.o: src/stb_image.c
	$(CC) $< -o $@ -c $(CFLAGS)

$(OUT_DIR)/libstb-image.a: $(OUT_DIR)/stb_image.o
	$(AR) rcs $@ $^
